version: '3'

services:
  db:
    image: mongo:4.1.8-xenial
    env_file: .env
    volumes:
      - dbdata:/data/db

  app:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1001}
        GROUP_ID: ${GROUP_ID:-1001}
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - HOST=localhost
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
    depends_on:
      - db

  metrics:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1001}
        GROUP_ID: ${GROUP_ID:-1001}
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    volumes:
      - .:/home/app
    depends_on:
      - db
    command: "./start_metrics.sh"

volumes:
  dbdata:
  node_modules:
